[tool.black]
line-length = 80

[tool.isort]
known_first_party = "myia,debug"
known_third_party = "torch,torchvision,tvm,hrepr,buche,breakword,docopt,gym"
multi_line_output = 3
include_trailing_comma = true
combine_as_imports = true

[tool.coverage.run]
omit = [
    "conftest.py",
    "setup.py",
    "tests/*",
    "debug/*",
    "myia/debug/*",
    "examples/*",
]

[tool.coverage.report]
exclude_lines = [
    "@pyoverload",
    "@abstractmethod",
    "@compile",
    "@core",
    "@wrap_grad_transform",
    "@bprop_to_grad_transform",
    "pragma: no cover",
    "AssertionError",
    "NotImplementedError",
    "untested_legacy",
]
